/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AuroraPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LoadDefault": {
      "type": "sst.sst.Linkable"
      "value": {
        "LoadDefaults": boolean
        "baseDomain": string
        "cors": {
          "additionalDev": any
        }
        "domains": {
          "api": {
            "latest": {
              "demo": string
              "dev": string
              "prod": string
            }
          }
          "frontend": {
            "latest": {
              "demo": string
              "dev": string
              "prod": string
            }
          }
          "websocket": {
            "latest": {
              "demo": string
              "dev": string
              "prod": string
            }
          }
        }
        "emails": {
          "demo": string
          "dev": string
          "prod": string
        }
        "getCorsOrigins": {
        }
        "getDomainName": {
        }
        "getEmail": {
        }
        "getStageMap": {
        }
        "getVersion": {
        }
        "version": {
          "latest": string
        }
      }
    }
    "PostConfirmationFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UserApprovalEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "authFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "brain_sqs_mcp_responseHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "brain_wss_mcp_responseHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "brain_wss_terminalHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "brainsOS_API": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "brainsOS_RDS_Aurora": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "brainsOS_RDS_Vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "brainsOS_bucket_email": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "brainsOS_bucket_logs": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "brainsOS_frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "brainsOS_identityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "brainsOS_queue_mcp_server_request": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "brainsOS_queue_mcp_server_response": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "brainsOS_queue_metrics": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "brainsOS_systemData": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "brainsOS_userData": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "brainsOS_userPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "brainsOS_userPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "brainsOS_wss": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "llm_gateway_wss_chatFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "mcp_server_queue_handlerFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "mcp_server_wss_requestHandlerFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "writeMetricsFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "wss_connectHandlerFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "wss_defaultHandlerFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "wss_disconnectHandlerFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}